### ISSUE TITLE
doesnt work on workspaces

### ISSUE THREAD

**Issue by FU3X** [taiyuuki/vscode-cargo-scripts#1]
[workspace]
members = [
    "encryptor",
    "decryptor",
    "file_fetcher",
]

resolver = "2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.scripts]
run = "cargo run"
check = "cargo check"
build = "cargo build"
release = "cargo build --release"

**Comment by taiyuuki** [comment]
Ok, I'll fix this later.
