### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by joeyame** [taiyuuki/vscode-cargo-scripts#3]
I'm not sure if it's just me, but my environment is pretty updated and I keep running into this error when I try to use this extension:

`Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.`

**Comment by taiyuuki** [comment]
I'm also not sure what caused this error, it looks like an error prompt from some testing framework, Can you provide more detailed information? such as a minimal reproduction to reopen the issue.

**Comment by sbeardsley** [comment]
I also get this error. 

`2024-06-29 19:01:44.958 [error] An error occurred when deactivating the extension 'taiyuuki.vscode-cargo-scripts':
2024-06-29 19:01:44.981 [error] TypeError: Cannot read properties of undefined (reading 'subscriptions')
    at Object.deactivate (/Users/sbeardsley/.vscode/extensions/taiyuuki.vscode-cargo-scripts-0.2.4/src/index.ts:94:11)`

**Comment by taiyuuki** [comment]
> I also get this error.
> 
> `2024-06-29 19:01:44.958 [error] An error occurred when deactivating the extension 'taiyuuki.vscode-cargo-scripts': 2024-06-29 19:01:44.981 [error] TypeError: Cannot read properties of undefined (reading 'subscriptions') at Object.deactivate (/Users/sbeardsley/.vscode/extensions/taiyuuki.vscode-cargo-scripts-0.2.4/src/index.ts:94:11)`

It seems that the extension cannot find any subscriptions when it is deactivated. This is not a common error, but I tried to fix it by updating the extension. You can check if the error still exists.

**Comment by sbeardsley** [comment]
I was able to debug the extension and find the issue. 
The exception is being thrown from the TOML package and not from the extension.

When using a workspace and and a workspace member references a value from the workspace's Cargo.toml the key naming convention is {key}.workspace = true. I use  `cargo ws` command to create my workspace member packages. It is what generates these keys. 

```
[package]
name = "backlog"
edition = "2021"
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
include.workspace = true

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
core = { path = "../core" }
infra = { path = "../infra" }
tokio = { version = "1.38.0", features = ["full"] }

``` 

According to the [TOML v1 spec](https://toml.io/en/v1.0.0#keys) bare keys may only contain ASCII letters, ASCII digits, underscores, and dashes (A-Za-z0-9_-)

So the TOML parser is correct. 

I have submitted a [Pull Request](https://github.com/taiyuuki/vscode-cargo-scripts/pull/4) with a regex to alleviate the exception in the extension.
